### ISSUE TITLE
Allow more project directories

### ISSUE THREAD

**Issue by popey456963** [gavanw/voxelquestiso#8]
It would seem a simple fix in order to remove the requirement of file locations and replace them with variables.  The most obvious choice of location to store these variables would be as environment variables which could be set via the following command:

```
SET install_location=C:\wamp\www\voxelquestiso
```

As far as I can see, the location of the folder is set in five locations, one of which is a markdown file that can safely be removed.  The other locations, can simply be changed to use this new environment variable.  In `cleanup.bat`, `debug_cleanup.bat` and `cleanupall.bat`, all references of the file path will have to be replaced with `%install_location%` and in `VoxelQuest.vcxproj`, the path can be replaced with `$(install_location)`.  

However, we run into issues when install_location has not been defined, which might confuse people.  So I'd suggest having an initial batch file that is always run contain a test for it.

```
IF "%install_location%" == "" GOTO INSTALL_LOCATION_NOT_FOUND
:INSTALL_LOCATION_FOUND
:: Install location was found successfully
GOTO END
:INSTALL_LOCATION_NOT_FOUND
:: Install location was not found.  Using default
@ECHO The install_location environment variable was NOT detected, using default.
SET install_location=C:\wamp\www\voxelquestiso
GOTO END
:END
```

**Comment by gavanw** [comment]
Another user has fixed the issue of absolute paths, or at least it has been fixed in my testing of it!

**Comment by popey456963** [comment]
Ah, that's cool!  You should edit the readme then =)

`This project currently MUST exist at C:\wamp\www\voxelquestiso. This is bad, I know, see above. If you want to change this path, simply open the entire folder in an editor like Sublime Text and replace all instances of "C:\wamp\www\voxelquestiso" with your own directory.`

**Comment by gavanw** [comment]
@popey456963 thanks, forgot to edit the install instructions. Fixed it
